fix test assertion
Before:

```
      AssertionError: expected [ '.gitattributes', …(5) ] to deeply equal [ '.gitattributes', …(4) ]
      + expected - actual

         ".mocharc.js"
         "eslint.config.js"
         "package.json"
         "test/helpers/chai.js"
      -  "test/helpers/mocha.js"
       ]
```

after

```
AssertionError: expected [ '.gitattributes', …(5) ] to include 'missing'
```